CREATE TABLE block (
       id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       hash TEXT NOT NULL,
       height INT NOT NULL,
       paid BOOLEAN DEFAULT FALSE NOT NULL,
       orphaned BOOLEAN DEFAULT FALSE NOT NULL,
       expected_reward BIGINT NOT NULL,
       difficulty BIGINT NOT NULL,
       created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE miner (
       id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       wallet_address TEXT NOT NULL UNIQUE,
       created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE share (
       id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       miner_id INT REFERENCES miner(id) ON DELETE CASCADE NOT NULL,
       difficulty INT NOT NULL,
       created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE transaction (
       id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       block_id INT REFERENCES block(id) ON DELETE CASCADE NOT NULL,
       hash TEXT NOT NULL,
       created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
