/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_offtopica_moneropool_util_NativeUtils */

#ifndef _Included_uk_offtopica_moneropool_util_NativeUtils
#define _Included_uk_offtopica_moneropool_util_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_offtopica_moneropool_util_NativeUtils
 * Method:    getHashingBlob
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_offtopica_moneropool_util_NativeUtils_getHashingBlob
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
